// Code generated by some tool. DO NOT EDIT.

// This file simulates a generated file that should be excluded from analysis.
// The violation below should NOT be reported because generated files are always skipped.
package internal

import "gorm.io/gorm"

// generatedReuse would be a violation in normal code, but this file is generated.
// This should NOT trigger any warnings.
func generatedReuse(db *gorm.DB) {
	q := db.Model(&User{}).Where("generated = ?", true)
	q.Find(&[]User{})
	q.Count(new(int64)) // This would normally be a violation, but generated files are excluded
}
