// Code generated by hand. DO NOT EDIT.

package linedirective

import "gorm.io/gorm"

// Generated files are skipped even when a //line directive renames them
// (issue #151).

//line generated.tmpl:1
func reuseInGeneratedBelowLineDirective(db *gorm.DB) {
	q := db.Where("active = ?", true)
	q.Find(nil)
	q.Count(nil)
}
