// Code generated by some tool. DO NOT EDIT.

package filefilterskip

import "gorm.io/gorm"

// badReuseInGenerated would normally be reported, but generated files are always skipped.
func badReuseInGenerated(db *gorm.DB) {
	q := db.Model(&User{}).Where("generated = ?", true)
	q.Find(&[]User{})
	q.Count(new(int64))
}
