package main_test

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// lineDirectiveCases are the reproductions of issues #151, #152 and #153. Each
// case runs twice: as written, and as a control with every //line directive
// removed. Both runs must print the same report lines. want holds the output of
// the //line run and wantControl the output of the control, with "<dir>"
// standing for the package directory.
var lineDirectiveCases = []struct {
	name        string
	pkg         string // package to analyze, relative to the module root
	files       map[string]string
	want        []string
	wantControl []string
}{
	{
		name: "line-level ignore (#151)",
		pkg:  "ignore",
		files: map[string]string{"ignore/a.go": `package ignore

import "gorm.io/gorm"

//line fake.tmpl:1
func f(db *gorm.DB) {
	q := db.Where("active = ?", true)
	q.Find(nil)
	//gormreuse:ignore
	q.Count(nil)
}
`},
	},
	{
		name: "function-level ignore (#151)",
		pkg:  "funcignore",
		files: map[string]string{"funcignore/a.go": `package funcignore

import "gorm.io/gorm"

//line fake.tmpl:1
//gormreuse:ignore
func f(db *gorm.DB) {
	q := db.Where("active = ?", true)
	q.Find(nil)
	q.Count(nil)
}
`},
	},
	{
		name: "generated file (#151)",
		pkg:  "gen",
		files: map[string]string{"gen/a.go": `// Code generated by hand. DO NOT EDIT.

package gen

import "gorm.io/gorm"

//line fake.tmpl:1
func f(db *gorm.DB) {
	q := db.Where("active = ?", true)
	q.Find(nil)
	q.Count(nil)
}
`},
	},
	{
		name: "colliding adjusted lines (#151)",
		pkg:  "collide",
		files: map[string]string{"collide/a.go": `package collide

import "gorm.io/gorm"

func f(db *gorm.DB) {
	q := db.Where("active = ?", true)
	q.Find(nil)
	//gormreuse:ignore
	q.Count(nil)
}

//line a.go:5
func g(db *gorm.DB) {
	q := db.Where("active = ?", true)
	q.Find(nil)
	q.Count(nil)
}
`},
		want: []string{
			"<dir>/a.go:8: *gorm.DB reused: second branch from mutable root (root at a.go:6, first branch at a.go:7); make the root immutable with .Session(&gorm.Session{})",
		},
		wantControl: []string{
			"<dir>/a.go:15:9: *gorm.DB reused: second branch from mutable root (root at a.go:13, first branch at a.go:14); make the root immutable with .Session(&gorm.Session{})",
		},
	},
	{
		name: "same-line pure with a renamed file (#152)",
		pkg:  "purefile",
		files: map[string]string{"purefile/a.go": `package purefile

import "gorm.io/gorm"

//line fake.tmpl:1:1
func helper(q *gorm.DB) { //gormreuse:pure
	_ = q
}

func f(db *gorm.DB) {
	q := db.Where("base")
	helper(q)
	q.Find(nil)
}
`},
	},
	{
		name: "next-line pure on a closure (#152)",
		pkg:  "purelit",
		files: map[string]string{"purelit/a.go": `package purelit

import "gorm.io/gorm"

//line fake.tmpl:1
func f(db *gorm.DB) {
	//gormreuse:pure
	helper := func(q *gorm.DB) {
		_ = q
	}
	q := db.Where("base")
	helper(q)
	q.Find(nil)
}
`},
	},
	{
		name: "pure function in another package (#152)",
		pkg:  "dep/user",
		files: map[string]string{
			"dep/dep.go": `package dep

import "gorm.io/gorm"

//line fake.tmpl:1
//gormreuse:pure
func Helper(q *gorm.DB) {
	_ = q
}
`,
			"dep/user/user.go": `package user

import (
	"gorm.io/gorm"

	"example.com/repro/dep"
)

func f(db *gorm.DB) {
	q := db.Where("base")
	dep.Helper(q)
	q.Find(nil)
}
`,
		},
	},
	{
		name: "same-line pure without a column (#153)",
		pkg:  "purecol",
		files: map[string]string{"purecol/a.go": `package purecol

import "gorm.io/gorm"

//line a.go:5
func helper(q *gorm.DB) { //gormreuse:pure
	_ = q
}

func f(db *gorm.DB) {
	q := db.Where("base")
	helper(q)
	q.Find(nil)
}
`},
	},
	{
		name: "same-line pure on a closure without a column (#153)",
		pkg:  "purelitsame",
		files: map[string]string{"purelitsame/a.go": `package purelitsame

import "gorm.io/gorm"

//line a.go:5
func f(db *gorm.DB) {
	helper := func(q *gorm.DB) { //gormreuse:pure
		_ = q
	}
	q := db.Where("base")
	helper(q)
	q.Find(nil)
}
`},
	},
	{
		name: "pure on semicolon-separated closures without a column (#153)",
		pkg:  "semicol",
		files: map[string]string{"semicol/a.go": `package semicol

import "gorm.io/gorm"

//line a.go:5
func f(db *gorm.DB) {
	//gormreuse:pure
	a := func(q *gorm.DB) { _ = q }; b := func(q *gorm.DB) { q.Find(nil) }
	q := db.Where("base")
	a(q)
	b(q)
	q.Find(nil)
}
`},
		want: []string{
			"<dir>/a.go:11: *gorm.DB reused: second branch from mutable root (root at a.go:8, first branch at a.go:10); make the root immutable with .Session(&gorm.Session{})",
		},
		wantControl: []string{
			"<dir>/a.go:11:8: *gorm.DB reused: second branch from mutable root (root at a.go:8, first branch at a.go:10); make the root immutable with .Session(&gorm.Session{})",
		},
	},
}

// TestLineDirectiveE2E builds the command and runs it on the reproductions of
// issues #151, #152 and #153, each in its own module with gorm.io/gorm replaced
// by the testdata stub, so no network is needed.
func TestLineDirectiveE2E(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not available")
	}

	bin := filepath.Join(t.TempDir(), "gormreuse")
	if out, err := exec.Command("go", "build", "-o", bin, ".").CombinedOutput(); err != nil {
		t.Fatalf("build failed: %v\n%s", err, out)
	}

	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	stub, err := os.ReadFile(filepath.Join(filepath.Dir(file), "..", "..", "testdata", "src", "gorm.io", "gorm", "gorm.go"))
	if err != nil {
		t.Fatal(err)
	}

	for _, tc := range lineDirectiveCases {
		for _, control := range []bool{false, true} {
			name, want := tc.name, tc.want
			if control {
				name, want = tc.name+" control", tc.wantControl
			}
			t.Run(name, func(t *testing.T) {
				t.Parallel()
				// The driver prints real paths, so resolve symlinks in the
				// temporary directory (/var -> /private/var on macOS).
				root, err := filepath.EvalSymlinks(t.TempDir())
				if err != nil {
					t.Fatal(err)
				}
				writeFile(t, filepath.Join(root, "go.mod"), "module example.com/repro\n\ngo 1.27.0\n\nrequire gorm.io/gorm v0.0.0\n\nreplace gorm.io/gorm => ./gormstub\n")
				writeFile(t, filepath.Join(root, "gormstub", "go.mod"), "module gorm.io/gorm\n\ngo 1.27.0\n")
				writeFile(t, filepath.Join(root, "gormstub", "gorm.go"), string(stub))
				for path, src := range tc.files {
					if control {
						src = removeLineDirectives(src)
					}
					writeFile(t, filepath.Join(root, path), src)
				}

				cmd := exec.Command(bin, "./"+tc.pkg)
				cmd.Dir = root
				cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod", "GOPROXY=off", "GOWORK=off")
				out, err := cmd.CombinedOutput()

				wantExit := 0
				if len(want) > 0 {
					wantExit = 3
				}
				exit := 0
				if exitErr, ok := errors.AsType[*exec.ExitError](err); ok {
					exit = exitErr.ExitCode()
				} else if err != nil {
					t.Fatalf("run failed: %v\n%s", err, out)
				}

				dir := filepath.Join(root, filepath.FromSlash(tc.pkg))
				got := strings.TrimSpace(strings.ReplaceAll(string(out), dir, "<dir>"))
				if got != strings.Join(want, "\n") || exit != wantExit {
					t.Errorf("exit=%d, output:\n%s\nwant exit=%d, output:\n%s", exit, got, wantExit, strings.Join(want, "\n"))
				}
			})
		}
	}
}

// removeLineDirectives drops every //line directive from src.
func removeLineDirectives(src string) string {
	var lines []string
	for line := range strings.SplitSeq(src, "\n") {
		if !strings.HasPrefix(line, "//line ") {
			lines = append(lines, line)
		}
	}
	return strings.Join(lines, "\n")
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// ignoreForm, pureForm and inputForm are the reproductions of issue #156. Each
// has one directive comment, written as %s, above code that reuses a *gorm.DB.
const (
	ignoreForm = `package p

import "gorm.io/gorm"

func F(db *gorm.DB) {
	var n int64
	q := db.Where("active = ?", true)
	q.Find(nil)
	%s
	q.Count(&n)
}
`
	pureForm = `package p

import "gorm.io/gorm"

%s
func withTenant(db *gorm.DB) *gorm.DB {
	return db.Session(&gorm.Session{}).Where("tenant_id = ?", 1)
}

func F(db *gorm.DB) {
	var n int64
	withTenant(db).Find(nil)
	db.Count(&n)
}
`
	inputForm = `package p

import "gorm.io/gorm"

%s
func withFreshDB(cb func(*gorm.DB) error, db *gorm.DB) error {
	return cb(db.Session(&gorm.Session{}))
}

func F(db *gorm.DB) {
	var n int64
	_ = withFreshDB(func(q *gorm.DB) error {
		q.Find(nil)
		q.Count(&n)
		return nil
	}, db)
}
`
	// generatedPrefix makes a form a generated file, where nothing is reported.
	generatedPrefix = "// Code generated by hand. DO NOT EDIT.\n\n"
)

const (
	ignoreReuse  = "<dir>/a.go:10:9: *gorm.DB reused: second branch from mutable root (root at a.go:7, first branch at a.go:8); make the root immutable with .Session(&gorm.Session{})"
	pureReuse    = "<dir>/a.go:13:10: *gorm.DB reused: second branch from mutable root (root at a.go:10, first branch at a.go:12); make the root immutable with .Session(&gorm.Session{})"
	inputReuse   = "<dir>/a.go:14:10: *gorm.DB reused: second branch from mutable root (root at a.go:12, first branch at a.go:13); make the root immutable with .Session(&gorm.Session{})"
	wantNames    = " (want ignore, pure, immutable-return, immutable-param or immutable-input(name))"
	ignoreNoArgs = "<dir>/a.go:9:2: gormreuse:ignore takes no argument; write a reason after //"
)

// directiveFormCases are the forms from issue #156 and their controls. want
// is the whole output, with "<dir>" standing for the package directory.
var directiveFormCases = []struct {
	name string
	src  string
	want []string
}{
	{"ignore", fmt.Sprintf(ignoreForm, "//gormreuse:ignore"), nil},
	{"ignore with reason", fmt.Sprintf(ignoreForm, "//gormreuse:ignore // reason"), nil},
	{"ignore with reason without space", fmt.Sprintf(ignoreForm, "//gormreuse:ignore//reason"), nil},
	{"ignore with want", fmt.Sprintf(ignoreForm, `//gormreuse:ignore // want "x"`), nil},
	{"no directive", fmt.Sprintf(ignoreForm, "// nothing"), []string{ignoreReuse}},
	{"ignore with dash reason", fmt.Sprintf(ignoreForm, "//gormreuse:ignore - reason"), []string{ignoreNoArgs, ignoreReuse}},
	{"ignore with words", fmt.Sprintf(ignoreForm, "//gormreuse:ignore intentional reuse"), []string{ignoreNoArgs, ignoreReuse}},
	{"misspelled ignore", fmt.Sprintf(ignoreForm, "//gormreuse:ignor"), []string{"<dir>/a.go:9:2: unknown directive gormreuse:ignor" + wantNames, ignoreReuse}},
	{"typo in an ignore list", fmt.Sprintf(ignoreForm, "//gormreuse:ignore,ignor"), []string{"<dir>/a.go:9:2: unknown directive gormreuse:ignor" + wantNames, ignoreReuse}},
	{"typo in a generated file", generatedPrefix + fmt.Sprintf(ignoreForm, "//gormreuse:ignor"), nil},
	{"pure", fmt.Sprintf(pureForm, "//gormreuse:pure"), nil},
	{"pure with reason", fmt.Sprintf(pureForm, "//gormreuse:pure // reason"), nil},
	{"misspelled pure", fmt.Sprintf(pureForm, "//gormreuse:pur"), []string{"<dir>/a.go:5:1: unknown directive gormreuse:pur" + wantNames, pureReuse}},
	{"typo in a pure list", fmt.Sprintf(pureForm, "//gormreuse:pure,imutable-return"), []string{"<dir>/a.go:5:1: unknown directive gormreuse:imutable-return" + wantNames, pureReuse}},
	{"typo first in a list", fmt.Sprintf(pureForm, "//gormreuse:immutable-return,pur"), []string{"<dir>/a.go:5:1: unknown directive gormreuse:pur" + wantNames, pureReuse}},
	{"immutable-input", fmt.Sprintf(inputForm, "//gormreuse:immutable-input(cb)"), nil},
	{"immutable-input with reason", fmt.Sprintf(inputForm, "//gormreuse:immutable-input(cb) // reason"), nil},
	{"unclosed immutable-input", fmt.Sprintf(inputForm, "//gormreuse:immutable-input(cb"), []string{"<dir>/a.go:5:1: malformed gormreuse:immutable-input(cb directive: write it as immutable-input(name)", inputReuse}},
	{"misspelled immutable-input", fmt.Sprintf(inputForm, "//gormreuse:imutable-input(cb)"), []string{"<dir>/a.go:5:1: unknown directive gormreuse:imutable-input(cb)" + wantNames, inputReuse}},
}

// TestDirectiveFormsE2E builds the command and runs it on each form from issue
// #156, in a module with gorm.io/gorm replaced by the testdata stub, so no
// network is needed. It checks the whole output and the exit code.
func TestDirectiveFormsE2E(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not available")
	}

	bin := filepath.Join(t.TempDir(), "gormreuse")
	if out, err := exec.Command("go", "build", "-o", bin, ".").CombinedOutput(); err != nil {
		t.Fatalf("build failed: %v\n%s", err, out)
	}

	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	stub, err := os.ReadFile(filepath.Join(filepath.Dir(file), "..", "..", "testdata", "src", "gorm.io", "gorm", "gorm.go"))
	if err != nil {
		t.Fatal(err)
	}

	for _, tc := range directiveFormCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			root, err := filepath.EvalSymlinks(t.TempDir())
			if err != nil {
				t.Fatal(err)
			}
			writeFile(t, filepath.Join(root, "go.mod"), "module example.com/repro\n\ngo 1.27.0\n\nrequire gorm.io/gorm v0.0.0\n\nreplace gorm.io/gorm => ./gormstub\n")
			writeFile(t, filepath.Join(root, "gormstub", "go.mod"), "module gorm.io/gorm\n\ngo 1.27.0\n")
			writeFile(t, filepath.Join(root, "gormstub", "gorm.go"), string(stub))
			writeFile(t, filepath.Join(root, "p", "a.go"), tc.src)

			cmd := exec.Command(bin, "./p")
			cmd.Dir = root
			cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod", "GOPROXY=off", "GOWORK=off")
			out, err := cmd.CombinedOutput()

			wantExit := 0
			if len(tc.want) > 0 {
				wantExit = 3
			}
			exit := 0
			if exitErr, ok := errors.AsType[*exec.ExitError](err); ok {
				exit = exitErr.ExitCode()
			} else if err != nil {
				t.Fatalf("run failed: %v\n%s", err, out)
			}

			got := strings.TrimSpace(strings.ReplaceAll(string(out), filepath.Join(root, "p"), "<dir>"))
			if got != strings.Join(tc.want, "\n") || exit != wantExit {
				t.Errorf("exit=%d, output:\n%s\nwant exit=%d, output:\n%s", exit, got, wantExit, strings.Join(tc.want, "\n"))
			}
		})
	}
}
